#!/usr/bin/env python

from qwer import asdf, qwer, rule
from testify import *

a = qwer('\d\d\d')
b = qwer('a', rule('a'))
c = qwer('a', rule('a'), rule('b'))
d = qwer('(?:', rule('b'), ')?', rule('c'))

pattern, x = d.compile()

equal('(?:(a(\d\d\d)))?(a(\d\d\d)(a(\d\d\d)))', pattern)
equiv([asdf('b', asdf('a')), asdf('c', asdf('a'), asdf('b', asdf('a')))], x)

equiv((2, [(2, asdf('a'))]), x[0].select(0, ('a',)))
equiv((6, [(4, asdf('a')), (6, asdf('a'))]), x[1].select(2, ('a',)))

equiv((2, []), x[0].select(0, ('c', 'a')))
equiv((6, [(4, asdf('a')), (6, asdf('a'))]), x[1].select(2, ('c', 'a')))

equiv((2, []), x[0].select(0, ('bogus',)))
equiv((6, []), x[1].select(2, ('bogus',)))

equal('(?:a\d\d\d)?a\d\d\da\d\d\d', str(d))

equal(123, int(a.match('123xyz')))
equal(3, len(a.match('123xyz')))
equal('123', str(a.match('123xyz')))

try:
  ok(False, a.match('xyz123xyz'))

except ValueError:
  ok(True)

equal(123, int(a.search('xyz123xyz')))
equal(3, len(a.search('xyz123xyz')))
equal('123', str(a.search('xyz123xyz')))

try:
  ok(False, a.search('xyz'))

except ValueError:
  ok(True)

equal('456', str(d.match('a123a456xyz').a[1]))

# iter()

equal(['123', '456'], map(str, d.match('a123a456xyz').a))
equal(['123', '456'], map(str, d.match('a123a456xyz')['a']))
equal(['123', '456', '789'], map(str, d.match('a123a456a789xyz').a))
equal(['456', '789'], map(str, d.match('a123a456a789xyz')['c a']))
equal(['456', '789'], map(str, d.match('a123a456a789xyz').c.a))
equal(['789'], map(str, d.match('a123a456a789xyz').c['b a']))

# int()

equal(123, int(d.match('a123a456xyz').a))
equal(123, int(d.match('a123a456xyz')['a']))
equal(123, int(d.match('a123a456a789xyz').a))
equal(456, int(d.match('a123a456a789xyz')['c a']))
equal(456, int(d.match('a123a456a789xyz').c.a))
equal(789, int(d.match('a123a456a789xyz').c['b a']))

# str()

equal('123', str(d.match('a123a456xyz').a))
equal('123', str(d.match('a123a456xyz')['a']))
equal('123', str(d.match('a123a456a789xyz').a))
equal('456', str(d.match('a123a456a789xyz')['c a']))
equal('456', str(d.match('a123a456a789xyz').c.a))
equal('789', str(d.match('a123a456a789xyz').c['b a']))

try:
  ok(False, d.match('a123a456xyz').bogus)

except AttributeError:
  ok(True)

try:
  ok(False, d.match('a123a456xyz')['bogus'])

except KeyError:
  ok(True)
