#!/usr/bin/env python

import qwer # TODO
import os, sys
from testify import *

modules = dict(sys.modules)
path = sys.path

sys.path = list(path)
sys.path.insert(0, os.path.dirname(__file__) + '/data')

import rfc5321 as a # TODO

for key in set(sys.modules) - set(modules):
  del sys.modules[key]

sys.path = list(path)
sys.path.insert(0, os.path.dirname(__file__) + '/data/qwer')

import rfc5321 as b # TODO

for key in set(sys.modules) - set(modules):
  del sys.modules[key]

for key in a.__dict__:
  if key not in ('__builtins__',
      '__doc__',
      '__file__',
      '__name__',
      '__package__',
      'qwer',
      'rfc5234',
      'rfc5322',
      'rule'):
    equal(getattr(b, key), getattr(a, key).bogus)
