#!/usr/bin/env python

import qwer
from testify import *

a = ('b', [5, [('a', [6, []])]])
b = ('c', [3, [('a', [4, [], a]), a]])
c = [0, [('b', [1, [('a', [2, []])], b]), b]]

equiv(([2, []], [4, [], a], [6, []]),
  qwer.select(('a',), c))

equiv(([4, [], a], [6, []]),
  qwer.select(('c', 'a'), c))

equiv(([6, []],),
  qwer.select(('c', 'b', 'a'), c))

equiv(([4, [], a],),
  qwer.select(('c', '>', 'a'), c))

equiv(([6, []],),
  qwer.select(('c', '>', 'b', 'a'), c))

equiv(([5, [('a', [6, []])]],),
  qwer.select(('a', '+', 'b'), c))

equiv(([6, []],),
  qwer.select(('a', '+', 'b', 'a'), c))

equiv(([1, [('a', [2, []])], b],),
  qwer.select(('b:first-child',), c))
