#!/usr/bin/env python

import qwer
from testify import *

a = ('b', qwer.asdf(5, ('a', qwer.asdf(6))))
b = ('c', qwer.asdf(3, ('a', qwer.asdf(4, sibling=a)), a))
c = qwer.asdf(0, ('b', qwer.asdf(1, ('a', qwer.asdf(2)), sibling=b)), b)

equiv((qwer.asdf(2, match=None), qwer.asdf(4, match=None, sibling=a), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('a',)))

equiv((qwer.asdf(4, match=None, sibling=a), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('c', 'a')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('c', 'b', 'a')))

equiv((qwer.asdf(1, ('a', qwer.asdf(2, match=None)), match=None, sibling=b), qwer.asdf(2, match=None), qwer.asdf(3, ('a', qwer.asdf(4, match=None, sibling=a)), a, match=None), qwer.asdf(4, match=None, sibling=a), qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('a',), ('b',), ('c',)))

equiv((qwer.asdf(4, match=None, sibling=a),),
  qwer.select(c, None, ('c', '>', 'a')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('c', '>', 'b', 'a')))

equiv((qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None),),
  qwer.select(c, None, ('a', '+', 'b')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('a', '+', 'b', 'a')))

equiv((qwer.asdf(1, ('a', qwer.asdf(2, match=None)), match=None, sibling=b),),
  qwer.select(c, None, ('b:first-child',)))

equiv((qwer.asdf(4, match=None, sibling=a),),
  qwer.select(c, None, ('c', '>', 'a:first-child')))

equiv((),
  qwer.select(c, None, ('a', '+', 'b:first-child')))

equiv((qwer.asdf(1, ('a', qwer.asdf(2, match=None)), match=None, sibling=b), qwer.asdf(2, match=None), qwer.asdf(4, match=None, sibling=a), qwer.asdf(6, match=None)),
  qwer.select(c, None, (':first-child',)))

equiv((qwer.asdf(4, match=None, sibling=a),),
  qwer.select(c, None, ('c', '>', ':first-child')))

equiv((),
  qwer.select(c, None, ('a', '+', ':first-child')))

equiv((qwer.asdf(1, ('a', qwer.asdf(2, match=None)), match=None, sibling=b), qwer.asdf(2, match=None), qwer.asdf(3, ('a', qwer.asdf(4, match=None, sibling=a)), a, match=None), qwer.asdf(4, match=None, sibling=a), qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('*',)))

equiv((qwer.asdf(4, match=None, sibling=a), qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('c', '*')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('c', '*', 'a')))

equiv((qwer.asdf(4, match=None, sibling=a), qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None)),
  qwer.select(c, None, ('c', '>', '*')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('c', '>', '*', 'a')))

equiv((qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None),),
  qwer.select(c, None, ('a', '+', '*')))

equiv((qwer.asdf(6, match=None),),
  qwer.select(c, None, ('a', '+', '*', 'a')))

equiv((qwer.asdf(1, ('a', qwer.asdf(2, match=None)), match=None, sibling=b), qwer.asdf(2, match=None), qwer.asdf(4, match=None, sibling=a), qwer.asdf(6, match=None)),
  qwer.select(c, None, ('*:first-child',)))

equiv((qwer.asdf(4, match=None, sibling=a), qwer.asdf(5, ('a', qwer.asdf(6, match=None)), match=None)),
  qwer.select(c, None, ('b', '+', 'c', 'b'), ('c', '>', 'a')))
